version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7-buster
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ .Branch }}-{{ checksum "setup.py" }}-{{ checksum "dev-requirements.txt" }}
            - deps-master-{{ checksum "setup.py" }}-{{ checksum "dev-requirements.txt" }}
      - run:
          name: Install test deps
          command: |
            # Use a virtual env to encapsulate everything in one folder for caching
            python -m venv .venv
            . .venv/bin/activate
            pip install -r dev-requirements.txt
      - save_cache:
          key: deps-{{ .Branch }}-{{ checksum "setup.py" }}-{{ checksum "dev-requirements.txt" }}
          paths:
            - ".venv"
            - "~/.cache"
      - run:
          name: run_tests
          command: |
            . .venv/bin/activate
            mkdir test-results
            pytest --junitxml=test-results/junit.xml
      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results
